name: Check BORS-NG has working day
on:
  push:
    branches:
      - staging
      - testing

jobs:
  bors-check-day-off:
    runs-on: ubuntu-latest
    steps:
      - name: Validate day of the week
        run: |
          if (($(date '+%u') <= 0 || $(date '+%u') >= 4)); then exit 1; fi